[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
estimate = { path = "../estimate" }
dotenv = "0.15.0"
sqlx = { version = "0.5", features = ["runtime-actix-rustls", "postgres", "uuid", "migrate", "macros", "offline"] }
actix-web = { version = "4.0.0-beta.13", features = ["rustls"] }
uuid = "1.0.0-alpha.1"
anyhow = "1.0.51"
serde = { version = "1.0", features = ["derive"] }