CREATE TABLE estimates
(
    id       int primary key GENERATED BY DEFAULT AS IDENTITY,
    estimate text NOT NULL
);

INSERT INTO estimates (id, estimate)
VALUES (1, 'Estimate 1'),
       (2, 'Estimate 2'),
       (3, 'Estimate 3'),
       (4, 'Estimate 4'),
       (5, 'Estimate 5');

CREATE TABLE assemblies
(
    id       int primary key GENERATED BY DEFAULT AS IDENTITY,
    assembly text NOT NULL
);

INSERT INTO assemblies (id, assembly)
VALUES (1, 'Assembly 1'),
       (2, 'Assembly 2'),
       (3, 'Assembly 3'),
       (4, 'Assembly 4');

CREATE TABLE estimate_assemblies
(
    estimate_id int REFERENCES estimates (id) ON UPDATE CASCADE ON DELETE CASCADE,
    assembly_id int REFERENCES assemblies (id) ON UPDATE CASCADE,
    quantity    int NOT NULL
);

INSERT INTO estimate_assemblies (estimate_id, assembly_id, quantity)
VALUES (1, 1, 100),
       (1, 2, 200),
       (2, 3, 300),
       (2, 4, 400);

-- CREATE TABLE projects
-- (
--     id   int primary key GENERATED BY DEFAULT AS IDENTITY,
--     name text NOT NULL
-- );
--
-- INSERT INTO projects
-- VALUES (1, 'Project 1'),
--        (2, 'Project 2'),
--        (3, 'Project 3');
--
-- CREATE TABLE project_estimates
-- (
--     project_id  int REFERENCES projects (id) ON UPDATE CASCADE,
--     estimate_id int REFERENCES estimates (id) ON UPDATE CASCADE ON DELETE CASCADE
-- );
--
-- INSERT INTO project_estimates (project_id, estimate_id)
-- VALUES (1, 1),
--        (1, 2),
--        (2, 3),
--        (2, 4),
--        (2, 5);
